version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
       bash -c "poetry run python src/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - envs/.env

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run python src/manage.py migrate"
    profiles:
      - migrate
    env_file:
      - envs/.env

  collectstatic:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run python src/manage.py collectstatic --noinput --clear"
    profiles:
      - collectstatic
    env_file:
      - envs/.env
